[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_demo = "3SLWpmiJPJbLT4MfnitHHoAZyuayThJMuEmkfMcxeX2o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/coolpp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
